Repository Lucs1590/Nkocr, pull requests merged in 2020-08, with the labels that each got.

#16 EAST
  .gitignore
  README.md
  requirements.txt
  setup.py
  src/auxiliary.py
  src/ocr_product.py
  src/ocr_table.py
  test/test_auxiliary.py
  test/test_ocr_product.py
  test/test_ocr_table.py
Labels: dependencies, enhancement, python

#20 Python refactoring
  src/auxiliary.py
  src/ocr_product.py
  src/ocr_table.py
  test/test_auxiliary.py
Labels: enhancement, feature_request, python

#21 Python patterns
  .gitignore
  README.md
  src/auxiliary.py
  src/nkocr.py
  src/ocr_product.py
  src/ocr_table.py
  test/test_auxiliary.py
  test/test_ocr_product.py
  test/test_ocr_table.py
Labels: bug, documentation, enhancement, python
